# Generated by Django 2.2.7 on 2019-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdatastore',
            name='data',
            field=models.TextField(),
        ),
    ]
