# Generated by Django 2.2.7 on 2019-12-05 07:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191205_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdatastore',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
