# Generated by Django 2.2.7 on 2019-12-05 07:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20191205_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdatastore',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
