# Generated by Django 2.2.7 on 2019-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20191205_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersdatastore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playersdatastore',
            name='filter_name',
            field=models.CharField(default='enter filter name', max_length=100),
        ),
        migrations.AddField(
            model_name='playersdatastore',
            name='table_name',
            field=models.CharField(default='enter table name', max_length=100),
        ),
    ]
