# Generated by Django 2.2.7 on 2019-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playersdatastore_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('app_id', models.CharField(max_length=200)),
            ],
        ),
    ]
