# Generated by Django 2.2.7 on 2019-12-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_appslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppsList',
        ),
    ]
