# Generated by Django 2.2.7 on 2019-12-24 12:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_delete_appslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key_Id', models.CharField(max_length=200)),
                ('AppId', models.CharField(max_length=200)),
                ('ParentId', models.CharField(max_length=200)),
                ('JsonData', jsonfield.fields.JSONField(blank=True, default={})),
                ('FileDownload', models.CharField(default='file name which will be downloaded', max_length=500)),
                ('DateUpdated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
