# Generated by Django 2.2.7 on 2020-01-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20191224_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppsList',
        ),
    ]
