# Generated by Django 2.2.7 on 2020-01-08 10:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_delete_appslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.CharField(max_length=200)),
                ('AppName', models.CharField(max_length=200)),
                ('ThumbUrl', models.CharField(max_length=200)),
                ('AppDesc', jsonfield.fields.JSONField(blank=True, default={})),
                ('AppOrder', models.CharField(default='file name which will be downloaded', max_length=500)),
                ('DateUpdated', models.CharField(max_length=100)),
            ],
        ),
    ]
