# Generated by Django 2.2.7 on 2020-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20200311_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appslist',
            name='ParentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
