# Generated by Django 2.2.7 on 2020-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_filesrelatedtoappslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesrelatedtoappslist',
            name='NodeId',
            field=models.CharField(max_length=100),
        ),
    ]
